name: "Run tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.3, 8.2]
        laravel: [11.*, 12.*]
        stability: [prefer-stable]
        include:
            - laravel: 12.*
              testbench: 10.*
              carbon: ^3.0
            - laravel: 11.*
              testbench: 9.*
              carbon: ^2.63

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

#      - name: Run security check
#        run: |
#          curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.6/local-php-security-checker_2.0.6_linux_amd64 --output /usr/local/bin/local-php-security-checker
#          vendor/bin/grumphp run --testsuite=security

      - name: Run syntax
        run: vendor/bin/grumphp run --testsuite=syntax

      - name: Run style checks
        run: |
          vendor/bin/grumphp run --testsuite=syntax
          vendor/bin/grumphp run --testsuite=style --tasks=phpcs
          vendor/bin/pint --test

      - name: Run static analysis
        run: vendor/bin/grumphp run --testsuite=static

      - name: Run unit tests
        run: vendor/bin/pest